name = "leledan-ws"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]
main = ".output/server/index.mjs"

[assets]
directory = ".output/public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "leledan-builds"
database_id = "9dbc22b2-8149-448d-a15d-2ec1ec011cd9"
migrations_dir = "server/database/migrations"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "leledan-uploads"
